<?php

return [
    'classes' => [
        'hsc_1' => 'HSC 1st Year',
        'hsc_2' => 'HSC 2nd Year',
    ],
    'sections' => [
        'science' => 'Science',
        'humanities' => 'Humanities',
        'business_studies' => 'Business Studies',
    ],
    'subjects' => [
        'common' => [
            'bangla_1st' => 'Bangla 1st',
            'bangla_2nd' => 'Bangla 2nd',
            'english_1st' => 'English 1st',
            'english_2nd' => 'English 2nd',
            'ict' => 'ICT',
        ],
        'by_section' => [
            'science' => [
                'physics_1st' => 'Physics 1st',
                'physics_2nd' => 'Physics 2nd',
                'chemistry_1st' => 'Chemistry 1st',
                'chemistry_2nd' => 'Chemistry 2nd',
                'biology_1st' => 'Biology 1st',
                'biology_2nd' => 'Biology 2nd',
                'higher_math_1st' => 'Higher Mathematics 1st',
                'higher_math_2nd' => 'Higher Mathematics 2nd',
            ],
            'business_studies' => [
                'accounting_1st' => 'Accounting 1st',
                'accounting_2nd' => 'Accounting 2nd',
                'economics_1st' => 'Economics 1st',
                'economics_2nd' => 'Economics 2nd',
                'history_1st' => 'History 1st',
                'history_2nd' => 'History 2nd',
                'islamic_study_1st' => 'Islamic Study 1st',
                'islamic_study_2nd' => 'Islamic Study 2nd',
                'finance_1st' => 'Finance 1st',
                'finance_2nd' => 'Finance 2nd',
                'business_management_1st' => 'Business Management 1st',
                'business_management_2nd' => 'Business Management 2nd',
                'production_management_1st' => 'Production Management 1st',
                'production_management_2nd' => 'Production Management 2nd',
                'statistics' => 'Statistics',
                'home_economics' => 'Home Economics',
            ],
            'humanities' => [
                'social_work_1st' => 'Social Work 1st',
                'social_work_2nd' => 'Social Work 2nd',
                'civics_1st' => 'Civics 1st',
                'civics_2nd' => 'Civics 2nd',
                'economics_1st' => 'Economics 1st',
                'economics_2nd' => 'Economics 2nd',
                'sociology_1st' => 'Sociology 1st',
                'sociology_2nd' => 'Sociology 2nd',
                'islamic_history_1st' => 'Islamic History 1st',
                'islamic_history_2nd' => 'Islamic History 2nd',
                'history_1st' => 'History 1st',
                'history_2nd' => 'History 2nd',
                'islamic_study_1st' => 'Islamic Study 1st',
                'islamic_study_2nd' => 'Islamic Study 2nd',
                'logic_1st' => 'Logic 1st',
                'logic_2nd' => 'Logic 2nd',
                'geography' => 'Geography',
                'psychology' => 'Psychology',
                'home_economics' => 'Home Economics',
            ],
        ],
    ],
    'subject_aliases' => [
        'bangla' => 'bangla_1st',
        'bangla_1' => 'bangla_1st',
        'bangla_2' => 'bangla_2nd',
        'bangla1st' => 'bangla_1st',
        'bangla2nd' => 'bangla_2nd',
        'english' => 'english_1st',
        'english_1' => 'english_1st',
        'english_2' => 'english_2nd',
        'english1st' => 'english_1st',
        'english2nd' => 'english_2nd',
        'bangla_1st_paper' => 'bangla_1st',
        'bangla_2nd_paper' => 'bangla_2nd',
        'english_1st_paper' => 'english_1st',
        'english_2nd_paper' => 'english_2nd',
        'bangla_1st_and_2nd_paper' => 'bangla_1st',
        'english_1st_and_2nd_paper' => 'english_1st',
        'information_communication_technology' => 'ict',
        'information_and_communication_technology' => 'ict',
        'i_c_t' => 'ict',
        'math_1st' => 'higher_math_1st',
        'math_2nd' => 'higher_math_2nd',
        'botany' => 'biology_1st',
        'zoology' => 'biology_2nd',
        'geography_1st' => 'geography',
        'geography_2nd' => 'geography',
        'math' => 'higher_math_1st',
        'higher_math' => 'higher_math_1st',
        'biology' => 'biology_1st',
        'physics' => 'physics_1st',
        'chemistry' => 'chemistry_1st',
        'history' => 'history_1st',
        'civics' => 'civics_1st',
        'social_work' => 'social_work_1st',
        'sociology' => 'sociology_1st',
        'islamic_history' => 'islamic_history_1st',
        'islamic_study' => 'islamic_study_1st',
        'logic' => 'logic_1st',
        'accounting' => 'accounting_1st',
        'finance' => 'finance_1st',
        'business_management' => 'business_management_1st',
        'production_management' => 'production_management_1st',
        'economics' => 'economics_1st',
        'home economics' => 'home_economics',
        'home_economics_1st' => 'home_economics',
        'home_economics_2nd' => 'home_economics',
    ],
    'absence_categories' => [
        'Sick',
        'Personal',
        'Family',
        'Other',
    ],
    'payment_modes' => [
        'Cash',
        'Bkash',
        'Nagad',
        'Bank Transfer',
    ],
    'expense_categories' => [
        'Supplies',
        'Salaries',
        'Rent',
        'Utilities',
        'Miscellaneous',
    ],
    'full_payment_exceptions' => [
        // Add student IDs here for always-full payment handling
    ],
];
